wifiwithme/apps/contribmap/urls.py
from django.conf.urls import url

from .views import (
    PublicJSON, PrivateJSON,
    add_contrib, manage_contrib, display_map, legal,  thanks)

urlpatterns = [
    url(r'^$', display_map, name='display_map'),
    url(r'^legal$', legal, name='legal'),
    url(r'^contribute/thanks/(?P<token>\w+)', thanks, name='thanks'),
    url(r'^contribute', add_contrib, name='add_contrib'),
    url(r'^manage/(?P<pk>\d+)', manage_contrib, name='manage_contrib'),
    url(r'^public.json$', PublicJSON.as_view(), name='public_json'),
    url(r'^private.json$', PrivateJSON.as_view(), name='private_json'),
]

wifiwithme/core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

def prefix(url_pattern):
    """
    :param url: url pattern, without leading "^"
    """
    return '^{}{}'.format(settings.URL_PREFIX, url_pattern)

urlpatterns = [
    url(prefix(r'accounts/login/$'), login, name='login'),
    url(prefix(r'accounts/logout/$'), logout, name='logout'),
    url(prefix(r'admin/'), admin.site.urls),
    url(prefix(r'map/'), include('contribmap.urls')),
    url(prefix(r''), include('pages.urls')),
]

wifiwithme/apps/contribmap/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from datetime import timedelta

from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.utils import timezone

from .fields import CommaSeparatedCharField
from .utils import add_one_year, ANGLES, merge_intervals


class ContribQuerySet(models.query.QuerySet):
    def expired(self):
        return self.filter(expiration_date__lte=timezone.now())

    def expired_in_days(self, ndays):
        return self.filter(
            expiration_date__lte=timezone.now() + timedelta(days=ndays))

    def expires_in_days(self, ndays):
        """ Returns only the data expiring in exactly that number of days

        Think about it as an anniversary. This function ignores
        minutes/seconds/hours and check only days.
        """
        return self.filter(
            expiration_date__date=timezone.now() + timedelta(days=ndays))


class Contrib(models.Model):
    CONTRIB_CONNECT = 'connect'
    CONTRIB_SHARE = 'share'

    id = models.AutoField(primary_key=True, blank=False, null=False)
    name = models.CharField(
        'Nom / Pseudo',
        max_length=30)
    contrib_type = models.CharField(
        'Type de contribution',
        max_length=10, choices=(
            (CONTRIB_CONNECT, 'Me raccorder à internet'),
            (CONTRIB_SHARE, 'Partager une partie de ma connexion')
        ), default=None)
    latitude = models.FloatField()
    longitude = models.FloatField()
    phone = models.CharField(
        'Téléphone',
        max_length=30, blank=True, default='')
    email = models.EmailField(blank=True)
    access_type = models.CharField(
        'Type de connexion',
        max_length=10, blank=True, choices=(
            ('vdsl', 'ADSL'),
            ('vdsl', 'VDSL'),
            ('fiber', 'Fibre optique'),
            ('cable', 'Coaxial (FTTLA)'),
        ))
    floor = models.PositiveIntegerField(
        'étage',
        blank=True, null=True)
    floor_total = models.PositiveIntegerField(
        "mombre d'étages",
        blank=True, null=True)
    orientations = CommaSeparatedCharField(
        blank=True, null=True, max_length=100)
    roof = models.BooleanField(
        'accès au toît',
        default=False)
    comment = models.TextField(
        'commentaire',
        blank=True, null=True)
    privacy_name = models.BooleanField(
        'nom/pseudo public',
        default=False)
    privacy_email = models.BooleanField(
        'email public',
        default=False)
    privacy_coordinates = models.BooleanField(
        'coordonnées GPS publiques',
        default=True)
    privacy_place_details = models.BooleanField(
        'étage/orientations publiques',
        default=True)
    privacy_comment = models.BooleanField(
        'commentaire public',
        default=False)
    date = models.DateTimeField(
        "date d'enregistrement",
        auto_now_add=True)
    expiration_date = models.DateTimeField(
        "date d'expiration",
        null=True, blank=True)

    STATUS_TOSTUDY = 'TOSTUDY'
    STATUS_TOCONNECT = 'TOCONNECT'
    STATUS_CONNECTED = 'CONNECTED'
    STATUS_WONTCONNECT = 'WONTCONNECT'

    CONNECTABILITY = (
        (STATUS_TOSTUDY, 'à étudier'),
        (STATUS_TOCONNECT, 'à connecter'),
        (STATUS_CONNECTED, 'connecté'),
        (STATUS_WONTCONNECT, 'pas connectable'),
    )

    status = models.CharField(
        blank=True,
        null=True,
        max_length=250,
        choices=CONNECTABILITY,
        default=STATUS_TOSTUDY)

    class Meta:
        managed = True
        db_table = 'contribs'
        verbose_name = 'contribution'

    PRIVACY_MAP = {
        'name': 'privacy_name',
        'comment': 'privacy_comment',
        'floor': 'privacy_place_details',
        'floor_total': 'privacy_place_details',
        'orientations': 'privacy_place_details',
        'roof': 'privacy_place_details',
        'angles': 'privacy_place_details',
    }

    PUBLIC_FIELDS = set(PRIVACY_MAP.keys())

    objects = ContribQuerySet.as_manager()

    def __str__(self):
        return '#{} {}'.format(self.pk, self.name)

    @property
    def angles(self):
        """Return a list of (start, stop) angles from cardinal orientations
        """
        # Cleanup
        if self.orientations is None:
            return []
        orientations = [o for o in self.orientations if o in ANGLES.keys()]
        # Hack to make leaflet-semicircle happy (drawing a full circle only
        # works with (0, 360))
        if len(orientations) == 8:
            return [[0, 360]]
        angles = [ANGLES[orientation] for orientation in orientations]
        angles.sort(key=lambda i: i[0])  # sort by x
        return merge_intervals(angles)

    def get_postponed_expiration_date(self, from_date):
        """ Computes the new expiration date

        :param from_date: reference datetime frow where we add our extra delay.
        """
        return add_one_year(from_date)

    def clean(self):
        # usefull only for data imported from bottle version
        if not self.date:
            self.date = timezone.now()
        if not self.expiration_date:
            self.expiration_date = self.get_postponed_expiration_date(
                self.date)

    def save(self, *args, **kwargs):
        if not self.pk:  # New instance
            self.date = timezone.now()
            self.expiration_date = self.get_postponed_expiration_date(
                self.date)
        super().save(*args, **kwargs)

    def is_public(self):
        return self.privacy_coordinates

    def is_expired(self):
        return self.expiration_date <= timezone.now()

    def _may_be_public(self, field):
        return field in self.PUBLIC_FIELDS

    def _is_public(self, field):
        return getattr(self, self.PRIVACY_MAP[field])

    def get_public_field(self, field):
        """ Gets safely an attribute in its public form (if any)

        :param field: The field name
        :return: the field value, or None, if the field is private
        """
        if self._may_be_public(field) and self._is_public(field):
            v = getattr(self, field)
            if hasattr(v, '__call__'):
                return v()
            else:
                return v

        else:
            return None

    def get_absolute_url(self, request=None, base_url=None):
        """ Get absolute url

        You can mention either `request` or `base_url` to get a full URL
        (starting with "http://" or "https://")

        :type request: request
        :param request: if mentioned, will be used to provide a full URL
        :param base_url: if mentioned, will be used to provide a full URL
        """
        url = '{}#{}'.format(
            reverse('display_map'), self.pk)
        if request:
            return request.build_absolute_uri(url)
        elif base_url:
            return '{}{}'.format(base_url, url)
        else:
            return url

    def make_management_url(self, token):
        return '{}{}?token={}'.format(
            settings.SITE_URL.strip('/'),
            reverse('manage_contrib', kwargs={'pk': self.pk}),
            token)

wifiwithme/apps/contribmap/views.py
import json
import datetime

from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.core.signing import BadSignature
from django.http import (
    JsonResponse, HttpResponseBadRequest, HttpResponseForbidden,
    HttpResponseNotFound)
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from django.views.generic import View
import pytz

from .forms import ManageActionForm, PublicContribForm
from .models import Contrib
from .decorators import prevent_robots
from .tokens import ContribTokenManager, URLTokenManager, TokenError
from .emails import send_contributor_email, send_moderator_emails
from .webhooks import send_moderator_webhook


@prevent_robots()
def add_contrib(request):
    if request.method == 'GET':
        form = PublicContribForm()
    elif request.method == 'POST':
        form = PublicContribForm(request.POST)

        if form.is_valid():
            contrib = form.save()
            mgmt_token = ContribTokenManager().mk_token(contrib)
            # Send notification email to site administrator
            admin_subject = get_template(
                'contribmap/mails/new_contrib_moderator_notice.subject')
            admin_body = get_template(
                    'contribmap/mails/new_contrib_moderator_notice.txt')

            send_moderator_emails(
                contrib, admin_subject, admin_body, mgmt_token, request)

            send_moderator_webhook(contrib, request)

            # Notification email to the author
            if contrib.email:
                author_subject = get_template(
                    'contribmap/mails/new_contrib_author_notice.subject')
                author_body = get_template(
                    'contribmap/mails/new_contrib_author_notice.txt')

                send_contributor_email(
                    contrib, author_subject, author_body, mgmt_token,
                    request=request)

            return redirect(reverse('thanks', kwargs={
                'token': mgmt_token,
            }))

    return render(request, 'contribmap/wifi-form.html', {
        'form': form,
        'isp': settings.ISP,
    })


def manage_contrib(request, pk):
    """ Contribution management by the user itself

    Auth is done by signed token
    """
    try:
        token = request.GET['token']
    except KeyError:
        return HttpResponseForbidden(
            'Missing authorization token')
    pk = int(pk)

    try:
        contrib = ContribTokenManager().get_instance_if_allowed(token, pk)

    except TokenError:
        return HttpResponseForbidden(
            'Bad signature, or expired token')

    else:
        if not contrib:
            return HttpResponseNotFound("Inexistant Contrib")

        wanabe_expiration_date = contrib.get_postponed_expiration_date(
            datetime.datetime.now(pytz.utc))
        if request.POST:
            action_form = ManageActionForm(request.POST)
            if not action_form.is_valid():
                return HttpResponseBadRequest('Action invalide')

            action = action_form.cleaned_data['action']
            if action == action_form.ACTION_DELETE:
                contrib.delete()
                messages.add_message(
                    request, messages.INFO,
                    'Votre demande a bien été supprimée.')
                return redirect(reverse('display_map'))

            elif action == action_form.ACTION_RENEW:
                contrib.expiration_date = wanabe_expiration_date
                contrib.save()
                messages.add_message(
                    request, messages.INFO,
                    "Votre demande a été prolongée jusqu'au {:%d/%m/%Y}".format(
                        contrib.expiration_date))
            else:
                return HttpResponseBadRequest('Action invalide')

        return render(request, 'contribmap/manage_contrib.html', {
            'contrib': contrib,
            'wanabe_expiration_date': wanabe_expiration_date,
            'delete_form': ManageActionForm({
                'action': ManageActionForm.ACTION_DELETE
            }),
            'renew_form': ManageActionForm({
                'action': ManageActionForm.ACTION_RENEW
            }),
            'messages': messages.api.get_messages(request),
            'isp': settings.ISP,
        })


def display_map(request):
    private_mode = request.user.is_authenticated()
    if private_mode:
        json_url = reverse('private_json')
    else:
        json_url = reverse('public_json')

    return render(request, 'contribmap/map.html', {
        'private_mode': private_mode,
        'json_url': json_url,
        'isp':settings.ISP,
    })


def thanks(request, token):
    try:
        contrib = ContribTokenManager().get_instance_if_allowed(token)
    except TokenError:
        return HttpResponseForbidden(
            'Bad signature, or expired token')

    return render(request, 'contribmap/thanks.html', {
        'isp': settings.ISP,
        'management_link': contrib.make_management_url(token),
        'contrib': contrib,
    })

def legal(request):
    return render(request, 'contribmap/legal.html', {
        'isp':settings.ISP,
    })

class JSONContribView(View):
    def get(self, request):
        return JsonResponse({
            "id": self.ID,
            "license": self.LICENSE,
            "features": self.get_features(),
        })

    PLACE_PROPERTIES = [
        'floor', 'angles', 'orientations', 'roof', 'floor', 'floor_total']


class PublicJSON(JSONContribView):
    ID = 'public'
    LICENSE = {
        "type": "ODC-BY-1.0",
        "url": "http:\/\/opendatacommons.org\/licenses\/by\/1.0\/"
    }

    def get_features(self):
        contribs = Contrib.objects.all()

        data = []
        for i in contribs:
            if not i.is_public():
                continue
            data.append({
                "id": i.pk,
                "type": "Feature",
                "geometry": {
                    "coordinates": [
                        i.longitude,
                        i.latitude
                    ],
                    "type": "Point",
                },
                "properties": {
                    "contrib_type": i.contrib_type,
                    "name": i.get_public_field('name'),
                    "place": {
                        k: i.get_public_field(k) for k in self.PLACE_PROPERTIES
                    },
                    "comment": i.get_public_field('comment'),
                }
            })
        return data


class PrivateJSON(JSONContribView):
    ID = 'private'
    LICENSE = {
        "type": "Copyright",
    }

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request, 'user') and request.user.is_staff:
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponseForbidden('Need staff access')

    def get_features(self):
        contribs = Contrib.objects.all()

        data = []
        for i in contribs:
            data.append({
                "id": i.pk,
                "type": "Feature",
                "geometry": {
                    "coordinates": [
                        i.longitude,
                        i.latitude,
                    ],
                    "type": "Point",
                },
                "properties": {
                    "contrib_type": i.contrib_type,
                    "name": i.name,
                    "place": {
                        k: getattr(i, k) for k in self.PLACE_PROPERTIES
                    },
                    "comment": i.comment,
                    "phone": i.phone,
                    "email": i.email
                }
            })
        return data

wifiwithme/apps/contribmap/templates/contribmap/legal.html
{% extends "base.html" %}

{% load obfuscate_email %}

{% block content %}

<h1>Mentions légales</h1>
{% if isp.CNIL.LINK and isp.CNIL.NUMBER %}
<p>
Les informations recueillies font l’objet d’un traitement informatique, déclaré
à la Commission nationale de l'informatique et des libertés (CNIL) sous le
numéro <a
href="{{ isp.CNIL.LINK }}">{{ isp.CNIL.NUMBER }}</a>.
</p>
{% endif %}

<p>
Conformément à la loi « informatique et libertés » du 6 janvier 1978 modifiée en
2004, vous bénéficiez d’un droit d’accès et de rectification aux informations
qui vous concernent, que vous pouvez exercer en vous adressant à {{ isp.EMAIL|obfuscate_email }}.
</p>

<p>
Vous pouvez également, pour des motifs légitimes, vous opposer au traitement des
données vous concernant.
</p>

<p>
Les données rendues publiques sont diffusées sous licence <a
href="http://opendatacommons.org/licenses/by/1.0/">Open Data Commons Attribution version
1.0</a> (ODC-BY 1.0) : elles sont librement réutilisables à la seule
condition d'en attribuer la paternité à {{ isp.NAME }}.
</p>
{% endblock content %}

wifiwithme/apps/contribmap/templates/contribmap/manage_contrib.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<style>
.jumbotron h2 {
  margin-top: 0px;
}

section.jumbotron {
  margin-bottom: 15px;
}

#map {
  margin-left: -15px;
  margin-right: -15px;
  margin-bottom: 15px;
//  margin-top: 30px;
}
</style>
<script src="{% static 'minimap.js' %}" type="text/javascript"></script>
<script src="{% static 'confirmation.js' %}" type="text/javascript"></script>
<h1>Gérer ma demande</h1>

<div id="map" data-lat="{{ contrib.latitude|stringformat:"f" }}" data-lon="{{ contrib.longitude|stringformat:"f" }}"></div>

<section class="jumbotron">

<h2>Prolonger ma demande</h2>

<p>
Sans intervention de votre part, votre demande, ainsi que les informations
personnelles associées seront supprimés de nos serveurs le
<strong>{{ contrib.expiration_date|date:"j F o" }}</strong> (au bout d'un an), conformément à <a
href="#">notre déclaration CNIL</a>, il vous faut donc la prolonger si vous
souhaitez que nous la conservions.
</p>

<form method="post" action="">
{% csrf_token %}
{{ renew_form.as_p }}
<button type="submit" class="btn btn-primary btn-lg"><span
class="glyphicon glyphicon-repeat"></span> Maintenir ma demande jusqu'au {{ wanabe_expiration_date|date:"j F o" }}</button>
</form>
</section>

<div class="jumbotron"">
<h2>Effacer ma demande</h2>
<p>
    Si vous supprimez votre demande, elle sera retirée de nos serveurs
immédiatement, ainsi que les informations personnelles associées.
</p>
<form method="post" action="">
{% csrf_token %}
{{ delete_form.as_p }}
<button type="submit" class="btn btn-danger btn-lg confirmation-protected">
    <span class="glyphicon glyphicon-trash"></span>
    Effacer ma demande
</button>
</form>

</div>
{% endblock %}

wifiwithme/apps/contribmap/templates/contribmap/map.html
{% extends "base.html" %}

{% load static %}

<!-- <span class="back-link">&larr; <a href="/">Accueil</a></span> -->


{% block content %}
<h1>Résultats {% if private_mode %}(données privées){% endif %}</h1>

<div id="map" class="results" data-json="{{ json_url }}"
    start_lon="{{ isp.LONGITUDE|stringformat:"f" }}" start_lat="{{ isp.LATITUDE|stringformat:"f" }}"
    start_zoom="{{ isp.ZOOM }}"></div>

<script src="{% static 'map.js' %}" type="text/javascript"></script>
<p>Légende : <br />
  <img src="{% static 'leaflet/images/marker-icon-red.png' %}" /> Personne souhaitant partager sa connexion Internet<br />
  <img src="{% static 'leaflet/images/marker-icon.png' %}" /> Personne souhaitant se connecter au réseau radio
</p>
<p>
  Télécharger le fichier <a href="{% url 'public_json' %}">GeoJSON</a>

{% if private_mode %}
(données privées ; à ne pas diffuser. Pour voir les données publiques, <a
href="{% url 'logout' %}">déconnecte-toi</a>).

{% else %}
(base de données mise sous
  licence <a href="http://opendatacommons.org/licenses/by/summary/">ODC-BY
  1.0</a>).<br />
{% endif %}
</p>

{% endblock content %}

wifiwithme/apps/contribmap/templates/contribmap/thanks.html
{% extends "base.html" %}

{% block content %}

<h1>Merci !</h1>

<p>
Votre contribution a bien été enregistrée.
</p>

<p>
Pour pouvoir la modifier ou la supprimer ultérieurement, veillez à bien conserver le lien suivant :

<a href="{{ management_link }}">{{ management_link }}</a>
</p>

{% if contrib.email %}
<p>
    Ce lien vous a également été envoyé par email.
</p>
{% endif %}

<p>
Si vous voulez <strong>rester en
contact</strong> avec {{ isp.NAME }}, nous rencontrer ou vous tenir informé, ça
se passe sur
<a href="{{ isp.URL_CONTACT }}">la page contact</a> de
l'association.
</p>

<p>
Vous pouvez consulter la <a href="{% url 'display_map' %}">carte publique avec toutes les autres contributions</a>.
</p>

{% endblock %}

wifiwithme/apps/contribmap/templates/contribmap/wifi-form.html
{% extends "base.html" %}

{% load bootstrap %}
{% load static %}

{% block body_class %}form{% endblock %}

{% block content %}
  <script src="{% static 'form.js' %}" type="text/javascript"></script>

  <header class="jumbotron">
    <div class="container">
        {% include "core/welcome_speech.html" %}
    </div>
  </header>

  <section role="main" class="container">
  <form role="form" method="post">{% csrf_token %}

{% if form.non_field_errors %}
    <div id="errors" class="bg-danger">
      {{ form.non_field_errors }}
    </div>
{% endif %}

    <h2>Contact</h2>

    <div class="form-group">
      <label for="name">Nom / Pseudo</label>
      {{ form.name|formcontrol }}
      {{ form.name.errors }}
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="email">Email</label>
        {{ form.email|formcontrol }}
        {{ form.email.errors }}
        <p class="help-block">
          <span class="glyphicon glyphicon-warning-sign"></span>
          Un moyen de contact au moins est nécessaire
        </p>
      </div>
      <div class="form-group col-md-6">
        <label for="phone">Téléphone</label>
        {{ form.phone|formcontrol }}
        {{ form.phone.errors }}
      </div>
    </div>


    <h2>Je souhaite</h2>
    <div id="id_contrib_type">
      {% for i in form.contrib_type %}
      <p class="radio">{{ i }}</p>
      {% endfor %}
    </div>

    <div id="contrib-type-share"
    <h2>Partager une connexion</h2>

    <h3>Type de connexion</h3>
    <div id="id_access_type">
      {% for i in form.access_type.subwidgets %}
        {% if i.data.value %}<p class="radio">{{ i }}</p>{% endif %}
      {% endfor %}
    </div>

    {{ form.access_type.errors }}
    </div>


  <h2>Ma localisation</h2>

    <div class="row">
      <div class="col-sm-6">
        <div id="map" data-json="{{geojson}}"
            start_lon="{{ isp.LONGITUDE|stringformat:"f" }}" start_lat="{{ isp.LATITUDE|stringformat:"f" }}"
            start_zoom="{{ isp.ZOOM }}"></div>
      </div>
      <div class="form-group col-sm-6">
        <div class="form-group form-group-lg form-inline">
          <input type="text" name="search"
                 id="search" placeholder="{{ isp.ADDRESS_EXAMPLE|default:"rue du calvaire, nantes" }}" class="form-control" />
          <span id="search-btn" class="btn btn-default btn-lg" data-loading-text="...">Recherche</span>

          <div id="search-results" class=""></div>
          <p class="help-block">Déplacer le marqueur bleu pour pointer précisément le bâtiment au besoin</p>
          <p class="help-block">
            Les ronds verts sont ceux renseignés par d'autres utilisateurs, vous
            pouvez aussi consulter <a href="{% url 'display_map' %}" target="_blank">la carte
            publique plus détaillée</a>.
          </p>

        </div>
        {{ form.latitude }}
        {{ form.longitude }}
        {% firstof form.latitude.errors form.latitude.errors %}
        </div>
      </div>

    <p class="help-block">Les antennes peuvent être positionées soit sur le toit soit aux fenêtres/balcons/velux.</p>

    <div class="form-group">
      <label for="orientation" />Orientation(s) de mes fenêtres, balcons ou velux</label>

    (<label class="checkbox-inline"><input type="checkbox" name="orientation-all" id="orientation-all" value="" />Vue à 360°</label>)
      <br>
{% for val, label in form.orientations.field.choices %}
    <label class="checkbox-inline">
      <input type="checkbox" class="orientation" name="orientations" value="{{ val }}"
             {% if val in form.orientations.value %}checked="yes"{% endif %}/>
      {{label}}
    </label>
{% endfor %}

    {{ form.orientations.errors }}

    <div class="form-group">
      <label for="roof">Je peux accéder à mon toit
        {{ form.roof }}
      {{ form.roof.errors }}
      </label>
    </div>
    <p class="form-inline">
      <label for="floor">Mon étage</label>
      {{ form.floor }}
      {{ form.floor.errors }}
      /
      {{ form.floor_total }}
      {{ form.floor_total.errors }}
    </p>

    <h2>Remarque/commentaire</h2>
    {{ form.comment|formcontrol }}
    {{ form.comment.errors }}


    <h2>Mes données</h2>
    {{ form.human_field|formcontrol }}

    <p class="help-block">
Les données collectées dans ce formulaire sont accessibles
au bureau de {{ isp.NAME }}.<br />

Vous pouvez cocher ci-dessous celles que vous voulez bien voir <a
href="{% url 'legal' %}">rendues publiques et librement réutilisées</a>.
    </p>

    <div class="form-group">
    <label for="privacy" />
J'autorise qu'apparaissent sur la carte publique :
    </label><br />
    </div>
    {% for i in form.privacy_fields %}
    <div class="checkbox">
      <label>
      {{ i }}
      {{ i.label }}
      </label>
    </div>
    {% endfor %}

    <input type="submit" value="Envoyer" class="btn btn-primary btn-lg"/>
  </form>
  </section>


<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Resultats" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
        <h4 class="modal-title" id="myModalLabel">Résultats</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

{% endblock %}